fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    exfile: "https://github.com/vicinus/exfile"
  symlinks:
    accounts: "#{source_dir}"
